# Generated by Django 5.2.6 on 2025-10-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatappTechjays', '0002_chat_delete_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_name',
            field=models.CharField(default='Chat 1', max_length=255),
        ),
    ]
